const PERMISSIONS = {
  // User permissions
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // Asset permissions
  VIEW_ASSETS: 'VIEW_ASSETS',
  CREATE_ASSET: 'CREATE_ASSET',
  UPDATE_ASSET: 'UPDATE_ASSET',
  DELETE_ASSET: 'DELETE_ASSET',

  // Liability permissions
  VIEW_LIABILITIES: 'VIEW_LIABILITIES',
  CREATE_LIABILITY: 'CREATE_LIABILITY',
  UPDATE_LIABILITY: 'UPDATE_LIABILITY',
  DELETE_LIABILITY: 'DELETE_LIABILITY',

  // Report permissions
  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',

  // Tenant permissions
  MANAGE_TENANT: 'MANAGE_TENANT',
};

const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.VIEW_ASSETS,
    PERMISSIONS.CREATE_ASSET,
    PERMISSIONS.UPDATE_ASSET,
    PERMISSIONS.DELETE_ASSET,
    PERMISSIONS.VIEW_LIABILITIES,
    PERMISSIONS.CREATE_LIABILITY,
    PERMISSIONS.UPDATE_LIABILITY,
    PERMISSIONS.DELETE_LIABILITY,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  USER: [
    PERMISSIONS.VIEW_ASSETS,
    PERMISSIONS.CREATE_ASSET,
    PERMISSIONS.UPDATE_ASSET,
    PERMISSIONS.DELETE_ASSET,
    PERMISSIONS.VIEW_LIABILITIES,
    PERMISSIONS.CREATE_LIABILITY,
    PERMISSIONS.UPDATE_LIABILITY,
    PERMISSIONS.DELETE_LIABILITY,
    PERMISSIONS.VIEW_REPORTS,
  ],
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
};

